replicaCount: 1

image:
  repository: dovanminh98/nginx-demo
  tag: 0.0.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: nginx-demo.lab.local
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 2
  periodSeconds: 5

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}

